[build]
  # Publish the raw 'src' folder (since index.html is inside it)
  publish = "src"

  # No build command needed (static HTML)
  command = "echo 'No build step required'"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA-style redirects (for client-side routing if needed)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Disable caching for JSON files (adds this new section)
[[headers]]
  for = "/*.json"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"