[build]
  publish = "src"
  command = "echo 'No build step required'"

# Environment variables
[build.environment]
  GITHUB_TOKEN = "@github_token"  # Set this in Netlify UI
  GITHUB_REPO = "DKTJONATHAN/ProtestAid"

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# SPA-style redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# JSON caching
[[headers]]
  for = "/*.json"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Access-Control-Allow-Origin = "*"

# HTML caching
[[headers]]
  for = "/pages/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
# netlify.toml - Add this if missing
[build.environment]
  GITHUB_TOKEN = "@github_token"