[build]
  # Point to your source directory
  publish = "src"
  # Or if you need to build first, set this to your build output directory
  # publish = "dist"
  
  # Set the base directory for your pages
  base = "src"

  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"

# Add this to handle client-side routing if you're using a SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200